language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - pehulja@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- gem install travis -v 1.8.8 --no-rdoc --no-ri
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=chapter10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=13.59.162.29
- export PLATFORM_TEST_NAME="chapter10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
env:
  global:
  - secure: hy7IHdTHcZkxrkCrjm9a2s9j6JrR0Fo84zE7DqT3H5gQeVMsT2RIa2L1/Qx64ipTKiR8K52pTUyuSt/P/elLOBmYKR+DtAR8WeJaw7RQMECK29bhTLw6CbIdY7YoX+cfeuSrk6/uTNhFXoLX8HrGzkiAzw3cgMfKs96f+SxhlUpX5luEDIg9bvKyEw9srCJJ3EMH3IAzV/ItwT/A8opi3ZfVPiC2wQOJfd6JywPCIJp6O1NkF6zSr8Xfhl/kTm4nrptoktiq4o46PCZ5cbG78RB2tWnoX7UOiW2wO5mKy+SqSuxA9Ql2a0CG0lm5b9F/gEOlZcC27R0dxZeG194jsNOymVt9AOZtEL2dNI/6hPWaNWOCU18WrzsLpvUSyJMtxIXoLGZE2fOzHZgBWhVF4kd7ht3vR0Qu1sJwTStFdXFsd5tLrGY6YXQM9hG4TZoaoaElHFByUYni0z+hJBcbgwkTrl26zO9kz50rU1FoAUeGvLHkEobgf/I9Nau4TOxK/2jVchbfAMz/RbIRd+rC2n1i6mQ8RX6g2kzuteyWpgrFE2FSz1pDuIw2uLgkIpV+jJVhAQuXHxBx07CSgkqLPOFiREFDMaySdsk4sofetPyYY59ZYU59m1h1R2li31h76YoNd15+LYjvgyEliFynyOoSH420XtBMFKNy+3TVmbI=
  - secure: nXkGFMKqYlcYYQjmSYurARkBlDQLDRqekEH/T/86Ld4VKJ/ZvKZTNN9hEvcpftIcqQUjaXwI2IwiINdMhserKerQoVhW5IlO1WnEwW2ylUWmXaTLFjnrMIHLqV0Tpn4MSqiKJVT3boUaRuNxQWxiRPU0fvb/tLcDQw7+eQtsoE5aPc5p7Wq9do7XYTHmz5eLh2tqg9C5tHRtk2vKFETkRvsp8eR23SOnUGrD+xPJiVrYhAzgO1Ir9ToVwVlvD/Q8RrycAIuq02etgVXiluNRJQ6PhWNED6lnrYHnV1m5AYmE1aZryzXUGTFSnul6y58D+cT5ppgbx3RP+tBMe9qEsefzVxc5uJ9eZpcLucg0wYtUBjeNkbDTXlowZWaHmqZXElLchdYN3BzRklZcKxvtnu5UYJT2Qp6IsDaCtfqDnwC1494d3FonD5QOlzfko4QHii1PZVvSNvh++ntNbKoixO25Uo95WlX6YRDuRjQznhwbCHx7L0WJPXE1W5M7ZgAAbmvzbze6E20zQL6CHOKoWoxaafLSq+J5adSFlfAFuJuohou126qWTv6fR67n7nfZ9qUyMTLWE22LggeA9MexdMY6azWcOj0nYGlqACeXGq9ApXDG2Zvg5jcsFJ6FxuwmVFurnjPppp4EDKZufR3ogzHmNJ6xcBZkjacoBrdrZxQ=
  - secure: a/Xq0pXe7eIoWrkNQgdJ1tKCTaGLsdU6jNbcXdKxdqb+PghaMEGIkDZLnN+qL3sMfCy4UldzudCCdT8Mz7H8AhqavHzi2sugzLK18D60pGi+rzcA+gTIigzi7dHcg765CaZ7fyXONojIEjQgm0sfiEGCdLK1WeY9Rfk88ruv6fEReXY0V+78hf87zdF5i5B+vULQr+ZSWZgNlmKPOFD1Xzak5tXKDZveDh2K/iF6toRD+qZt0qiaWoF5SeSZ4TLmoQkR9IG3Ev9f3ng1kGhBJnYRscAweQqv3oG8emTtb+qQ52Vs1sRjx7+R1lvfyDXaClWp01YTQ+y84WjUhBucxwe0mcLwkCMe1kO3LcOq5E9fI52SJHPO2drNXKdj53T9LZ0hEWU0cr2nhvk7HClyolLDTEI3bc6p01YdehwRLgA+QH6Ve3w4y8mrZtJU16p8CBHeWIjSYuPUuyWbvzMJ2nsCRfhCwzVyHksi9FewKOuZa4tCN2eghonkcC0ixgDKUZ8ytOG23eGUCjGMkXjEUJXyF1p7uCJAHopn5p0nDhS075nj+lw0j6X8okKSXNCRpJ1ee0HaINHDuiY/ICxeirfOwvyDFTvDr3SkuSzHquQ/ecHiWgzqH7E3tUczpVaM0wiAoZPqLLUERd3JTEHZ+WNiRcE3VZtCbg+D+qmIDkg=
  - secure: HnhcS27c28QozHEi9eRF0G4KaYmganYzJ1KKPESTn+XmNOd3PjVc+AGZQRDM/W9vADUOPQ/Bmm/vg9ZkFVGSvo3HV6tScHJuItydaZ35+KES54z0gXqtPakpUxr29Jhp68OCpxfD36NfxY1HJeN9jxdp09P8dcv4XzK+Z0Pi0N0xJ3OKAOBlVUmCCtlaUmWXqyiqQxbIaRxUvG88crefB0XYZZlaa4xMBgIPS7BmeL4OZ59WNrbKLoulBwTSAN91IqEFxLGRg7Ubs6aeJlQafdvY0x4Z7sHhb21chYVa93pGEDO40aWksklaTfO+0bcsL6LGy5r1xpnkFltqSG5UHtjEpMCC8AFrDWvo4yD4DlKrfDsZtXyyKb5o96mB6Bd2wSDYgc1NsPGk2lqsSwZkoj1pWlOY8eJ7rG1yXFj1tAS+cjQFL4ndNjAXGu6FTRJyfTWzOs5PWykJEWQNCuLM/01QiHT+nzh0/F881z+4TWMz2ZAXmFKr5bpwoRqt5G0LuXe2erk3k5C0qCTRuToXtdv7DIosfRC2TiCJjmKVQjOcwLriRL8wXBlYuYloaYMjwcewfl/obeRyWIQXcF4OPrSM1bMmTwN1uSRFdQBCfOoyA+CmwtjR4Bf+OvArySRCYfkjhmqRTOW2kZvsfZnCP2L1oY80tY/xcD5WQH4JTJA=
  - secure: HIiY3h/BsFvqY+anOKQ/eUnzgWp37MIdlV0ICAL4YHCzipeW2GpjmZTLw0yC4Z9RO8LIo6RHpcp0t1CUt6Beg6nVN36TbA2DXhwtSMAmdntgkCXR0CopsfmCf8Ed8nI78VHJGj0hb3OO8FxdNeKhvOpiz4a8JUrvnDzB3COegh7tR94cxSKHmdH4e/Rxf98rP0YikaCA68JgU1M135DrTdUr2yg9N77J3aRnx8+5OLkulSfo5qAYSTuF0X9SGpuEVr5GbNxyxNcJQIbtwFLX9JNVMb1TxOY7/HAus7bxHVBvdnioT6w5rrEJcQfCnVkcNcVcxXWc65IJC8d1MyTzANmmyR0RncJx5nFQ3kXHWBNwMNtUvRi2A0dM5ZQ0ESwMYBGNagusMsk62kvFVMkIZNlIXNgXpGbhG9e0BMiu07uHW7FAroZeLrXxuQY4rltQ5TnRc2Nb4JyjOnjn/kMR+mCiHbWMHp1Rb5F3ohNVdH/95V778nnZwnTugQNBLGE+X6LMLqHM1vCBYHld7Gcn8OXRW0vaT3oYwQQJP950d9a5DxMank+3EIabVl6VYsKP0159mkgc9giqzhxLll4sV2m0ecCwqv2smaTFOd9AchBL9kI7i9w0Yn6L7B9qGbNPpJFKummWTzileJTC4hQoW8EKz6XLYsQuBrSHKUioF0U=
