language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - pehulja@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- gem install travis -v 1.8.8 --no-rdoc --no-ri
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=chapter10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=13.59.162.29
- export PLATFORM_TEST_NAME="chapter10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
env:
  global:
  - secure: G9pXQjZ1z5mXfexA9EZfPb8/MJdBCqKlHlj9sNdGEBg1ilrjVxHKH9CIKqIQmgIseu3J4Hz+QynhAAXxAMDrX2EAIg1+4V6VB9t8fhqQZDpbSi1JD9MAKei3ryJFe3Y2CtENs2oc5CXvFaSHW98EHKcgHvCNCiJ8VSMnqqCEZ3Ugcf+tuMju7OSvSU8R/OMtOkt8mFCse53nAqtL69O8pz4MeWY0saLJiSFBnnhzTWA1WCKABviyE0NkU54u+f8IEUzqoUjchgEVpGTt1zu4ueKpVYi5n6AdolxktMaxx58iax5y6gHejZqrneYcA5mH3DjGNdvhmz/cBrVqcS+cqMaMU6rvx/piDGuHgNREZL9V944MEDOUQ5Rknfsc6wj1bzoEeD2bbhvh6q1YSAcZmMduYg4Q6yepjp21piVYXNQm4zi9q/8YfkMKI0B1EFSjKkKyKVi7uoiWNDFEp4CRJtL6ShWcH/8QWSCMxJbYZ2iZZTVWe5+Sa7/8QOMbbeN7LOHNzNSuEvXRfZE0p9mVL0Ioh/kjUUFAP2h9KIKBz2kE063jnWnAi1w/bBR790UxK5j0mQeUzXULVyRN7osB32OXP1R9/EfKDUhDYE3f0Swq1/VPpM9t07L0RdncCWi1lCyJrsnHFVQbPfMwhzPeUysFxNvoEdWhoJj+N9Zl7a0=
  - secure: LlS3lF8VKVj8elfGvrFRCYbxjVEeUT4SsdW7Rpl+SqjwQEKd0o+0cFoUVYqNBLC4mgEn5LLQnXFcVm6cPTwhEz7fMWw5XNQhQR2MyRRS38tQqo7VvRBaEhm8ZgqfMxI6MNOH+PgkTOQSM19YsEGuxJP1W3ACGDD5so4v1tbLcWtBDvi4/JWa3vfinwloowJ8kQV6H7b47zM9+TSrmBcP6ZXLTDDjYH8XC6JWt1aHozvrm3GSQiB/rhcUk5bUHyLGcIKi+qULrpxzd6IbNgmOmdSbHMkiPu5xn7qoASFGzJflw4inRSnEnmdgxPT2naJMeU7AulecaxuTByOoi0hWeCByCogHs3KLTSRLOO3SFXIsYdfnlY3u97cMOWA5N8UnAIA1f+NTi9/KUQOIMdjFTjtvbCrMdDrm7BHwiQ9Egja6lWmkwc3pndLdVkiePmQR8EOnSO6EoZK7EOooiue/SXWejAi98lHAa5M6I3DXwifrAXcvVQAPpIJtofdwKsdshQ2XYr4YX9+BjUzddITYrRD6AMnLyepBehXxBGMTiYIxPyZEE91N2FCCAShcjADiONQ//j6pQLOUgSc9pmqMxstcCfwBRhWczdRmXnbvzDZuBvMPwZnO1+y5UwC2Uxyo+0RqCBnv7oVZexG7LuTK6l/cMbl1hRli6MiM4t0Lnkk=
  - secure: WrLdBXnYk4h8TNMgg6IiDdXc54gVs/OtDWEzDkRlz4ucKzmfvU+sWNjFj/g7ofOkiomYgu3cYS6tHCJOQtbRzfevTKOTkllKS8KY6151YmGmiHiCaS2kcmu8I+kxmJiTjGHgYQnOqVbmwpG/jaXHDaKI480yzmhzh0npXaGuC6gqkZOZuQ+rW44AVCwdoVd3mPBWJHt9oq6onmSZIB4hupTJOn8f1sQ0P2pG94EqEWeh+6CnMUIN6fZHsc77EE4+gUIdkLs0S7DzZMBBhWhBqzlaH4Je63A/2B7KIISHYEIIQiX3iy/ofMtE82FWT52sNRptVk9POCSXKRK7ezZT7ELPffucHhrqsvfATKRRXX+sXSkUwQNUq2l/PhcdFcX/P4OPWz3U+ib2EQn5d5KL7jLScw48g6qD+L0Q31k9OU63vu20Xy6mec9TLQ63eV0kU1NPr/1pOs1V4Dyv0IUNYsPr1biYL9dPj9NhjBP7o1XHYExg55ti2UOnYon/W/ngQ3l183yanVl443h0WzidiDT+9Ecic6r5wImsvi73867rrTehCNk4HuqxDYLtF2lAXlhfxF4Ty743PSx5E9WhcmEQS+wtiYKGtI1qB+mM0RnkE3QVbU/s116cvU9e/9LKL1P1/PIR8MxNxzaBrA9gcPMrxeg3iVpbckR8gktBH1g=
  - secure: gNAyYjvnuxCpiDjvCThxcp2vOWnRVols/IcRqysQt9TS9k+uLGEulaBq0KtnvXvqtfAasZd44i3fB3ZZqaLQlhsxdfgDoWwyF6i+W95EE/2iaQjqDfYJoKxnqIi4RyxiY1u4QpvIbltVN++VjvwkY4/+GZRXsXpUeWlR7bJfSSAxloK3npAyJgpQLCp7PJ6zHuQYByz82VlCvrERQYHbURjMsTd6R+AVpcJ1WG+zfVyvv6A2ZAOl8bkBgbMT49ctyoRGVJ93+gVV+sf2QnsBJBLcyFDV0oV9+k6C30GDKLNpCCMDvYRCBpi9rSJuaB7dzBHjpexPNEkdVsz0um1GCKYTmydeVITLkK5A8fqZj1TO3i+zxpuZyy/9RjTJKrsbftT9LF2NZcwSNJ6ZG6leHVSkEm3f6sqshcJXhjNAcM0Q/8GO1ebpKxhSPZ4kWCAXfUCxnG5HD5NHzQqpqg541BEE0opvEKIoXqkWsjmyJ2CRAftn5RGtOnOwvJnGeQXjJDDrxHLyb4cNJgQFUpppJ36wEhLrBok3K4QVGA4rRpMK1Z4EvWjdx7zu3rY0vXcpaOcDhJMoVgJMdXHeVglH2iC69dbriJ7aPmue2BlWtbkq3aaF5vNmb5z6anCaXvrJSki9ps8FKrGqJIoxk+Bos84GvcKmUZuDqorOMrIFwJU=
  - secure: n9QRvZodnMK/dipqUoiJFEaAycjoiOjaSGR50BhG9hiz+9B12CkkNnxYCgnIWx4SzxQXzGSJo2OPWnOuhOBp53VSYn/AE16i/ORXT/rsbYqR8HQH+CxlnWHZ6uah/le2yoPZzgITfum7MZEwaf4zAX9cOkxpFC+6yVXwPrHYIl1DfcakuV5pzjgs+3RkuMA0Y3qUX+0p0undwKEPnPdvfAl64UHoEZ31bssRiwz+/zIb5GjWTH88M+sbYks+3pd1VCDU8wP4pExgQEOWn0BrwPtXH9PvnDTQqH0Xe9o/3XwFKUp8990zRIwngb8RdNP/YbIWPV6yJ19vSd7n5PW6mYETSR/rl+cel29vaI3XJH88lA1bLlRJ+Bpd4x/6nu9NkVuWxgk2d4VQLDQPP+6POx1S5YdR7FWTAYLWEVx3IdM3Ngv1uZIQY8FwtuKYjxnDUXI9P0zA0NIR1/t+xL2nWxF1ifJ1qGq/hCVdOQHKNqd4MzE0NDqfzAwECYp+2ZRUQVZbhWEVPAhROESmktpiBkHsbCnp63CbpvTVq7Ab/scPRqtAKtq8o73fThMPgun0HB3mB83tkjHIGaTwryaNFBqwGxzH/wLWvljwulqYqV5aHJPWBS20ziprRQMv0RWnmFA7llCItlOy4p84CIXrb8wsU/AdjrEggyxthoIAEfY=
