language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - pehulja@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: lXoShh1CXJiWEZ7xmgazsGJK2ppgV2pVR0KO6CoA/e2q/udo5XYxrkdF+3YDBxKltd8W2KAlmUtBgHYsLA0EHXeo5CJMY7n7Xm38a735EjI6lTSDorO9NhEGFtuQVZFhxyyy7P+SNBNa2Yv+TpJMIH+aWIL9d+RDarlIZIQZxvG3F171GUAJyYZWYkY5hGqPvWlz7CHkW08J7lzNi8whiJYTA6VHDqD43AOGJ7uSI3CUfixKGsPfqGStBDjmB3dNYFxa1aN2tSbTWpy3T0tKAaPTcs59kAvqdhgMxXIml/ByBk9eq3aarUKFJFNJ9DC0qFCLXnPV/Bw8ODj4AVWtd1TQQl+XXRWO/rKO77NMAVJRT1mP1teTXNRSUvim0/PQR1+l0epxekpNARrlgHtfqqJcOtbUoV9Vw1tjJ/9zyyxFc5siGi6pvqbTYZRqycEFplG6yE3ESo3Nz9bRo62DcGUW/kKUU4Dd671HZqnZkn6ggLP4RqY3+vQw9+5eGSn4VqDCwma0qTohK/j/1+9ia1RRv0kFclJ5ueeTsJCHco2eHnU1f4qC1WU1zwXbPS/j1SJieZw8rIM36mXeGYHW6bnv5DzLsjE56sUOpejgcjd3sKWvd5HKAsm0yL2T/FPsl/P9ivou5lA2ICqlTtzWbJkMaqJBOv8YzBz+ex9Q6u4=
  - secure: ExNIVZoO2Q3yFRVpT+5a1C5viePzPNRqkzwYxgE8yifPOjkBjEkLQa24Nbs7GgpWk0i9G69qeYs/Am0NYpHQ9ZBbXjaG6GDnQOIUnytIx8YnCCJFd3kg9sTZMPxF22mu5/SHOyG+QZZNEZgZTyEHYcoG6eQzsziiAPwEYd3KXFB9Wr9l4WhDCgcWBOZIDMIvY+13YqFUgHqmt+jq1wt8pwkaappyMau+9WTKlMcCRMpFls3ASUfJfs65c/lGz0cTbpEb1Dp1nYYiM12WCXfCspPBs8H5EGslQssLPzXknnSOur8Xu2oX5d8qfXocoWBc+j6aPbLT5cKe0l3pUksUcqZsUSmHI26wWaNwpwzyOWtQ3XSHQd5lEHFvpdjttg+6TJs5rZBnby32Z7qe3C/hmtdCsKXnpZPm4THsYZW6Zuz0FSXQuKNTby1858JI82+xTWT3ES0UT4EjR4jeCUTE8ECNIMAO7DEwRv0AyhY00MeQsj6cjntbJ+BV6slQ4YzAfFK69DP0s0/ZyIYc751lqWskqpwpbscHv+ApL68f22JRlcU9hy7r/TDmW7QPbq5ygQ1cZ+gKOVHuxquZjBwCUmFa5DM9KmGNQEcgxsu3JPZEzNQTsq7mfYdVImawBYxkTvoJQcRQtldwY3RdiAEqlIL+9RfVbDXOPbjO8s185AA=
  - secure: bVSXGcTucx4JuSDxljyY/qEkUTCzPWHX3r4FwbB27iWbQlN36x2dm4Ap7yzhzo1lySeXNWu5zBsvPCT8yrp5oLvjjH9mV8UToZviqBLG8HnXC/5OZCxGUcka7jYGgETP1QnYUUhVcW52XFpMihS6I7ZFnCCUW4gHGKUNjvlmZXjAmFfkUoTnbMqIQuOva+fnG2h167WaEN09DjZAq7Hv3VG/0l0BKsNiXQaxnWZChsDaqyMmI3KDsNt8b49+SqxEaIBRWqoFDL/Gvim1LhBLsU902dBIZLx2zxJrENCdKjEDN54s+NknCWWO+b+hW6euWB2+FO8rCSzOBKkAzghMWyKTDtMQ6OZcpaaXZBN2PQ7VWgazRDWiCk/VqUrG0If0i17QpBwZt+HUiGyd9RLbraxCh2BHkTwDjidK+JnNpkIRgJxtzAhUUx4Wr/RKxQLtQPx+B6+MRaquL7ZUkTgSVdV3lq5bw5eQi4yFqEVYo1pdZ5fiV0zWQM9DJTIw5MGyFIO7eQhNsqZjN4Mvp+qNDTa248yH9JjjkLrQ0AORywhPbBfuooRKlObvHgtNEeKLfTAGl3ZMWqw7IeZBdzp5jtNqwdJL2WnwthEM93GIO+PpaMb6bmxG1pgv3/PyVgCeQjitqd+RjZ8jNu/DAccv4cKNhyIXxafoNHeHAC/tgfA=
  - secure: MzSOjTnlMt2sptvc0n2aNzLk/T1rnkK/oqGRX5hIQatNzPOtjeWXWA5pePrFyLC07qD9vGnk3+KkyNoZaLm4H8HA1zx46zAJWR9JaFdBCFIRjkfpXu1lPnatAdFI2pyJ1fAkoniFQ6YIvSdeGMjWM9jkavgbDDE6FYJdBgzzx9XIp++nx2XNPGTLgxkDxzTQ/n7TC2XpkDbMzD3HptMATf4Pow7jEOCTZM4CEw51F+WbDWlL3pxKGvrsmdhDf1W0tiQTB42hLg9KKT6ZYnLPFE7CYq5XL3xKhgo1MWu6eL1Rx8kiaqyGV69eTTlpzq35h83jQeCCDajuDlBERt4vvyjMDHiqY68fZBfvEShOSzFsXSiWFJQi2IrAYTtmitDXhnQMalyiPncP9aKHUPH3x0dl2+5jd+jxZfsdd0XkjfruNKWiVlXPzMcdeyuLb2nMEOHCLOkrGyV3hOTcsllIAyBS8mLTQSuZR12toG9jmE0R6UpitAw/TKBaOd30pFzEjVtxRz8yJFGdtbOwA5BrYgQgOuoTKdmEdTrHua46jY5UCDTFKgqGYf5kzeS9QvxMP/mDRYF2C5GwCDufYVV0RLyJF4oBgS0rXKXl+z4EdIjioSJ/LiyDnzwBU2FooOL9SB3IDOdAj1tmQUOM02IIW3JRY0oVm2w67Og+4yKQ+v4=
  - secure: dJ8dLOTqAu9bS5cCyBDwM6XysBqFQqYQu5cV/lop1PjOdtBVeluBgvNwSvfoDUuDmyGCNko67L5Ch3aQ3SF5vxr8v0YemO6OT0P59gsxW+yDPm90Wb23+UZsEeCHZphm7TIRAX17nK+yA8USSG8f5PxysIR54RceVnA+wQj6XJsFmYPi9l/g+xqFl0257q7jMeCJ2jSSaU8E/SaLSAgVEEKwYv3StvGiY8NPQzQIGs/uxdr3gRi9GgpA/kjH4YFltvhLxrS3dWLEOsLmVqMK4nkKfSZegnMwQq7QARkG89MeB6RIFkd/UQIXcV9Lw8fSZ7qgJ38vAmJiTIoeve4tiBR8eOKUknGBRhIZFI9+V5j+59vkDuxZa2RcRzZ/M1pvQW9W/hXHNK9Lw55xwGEKcia/pb4dssBKOwj2kvyTjCoZ0UNL32+qSJbYGi4gTSNpjtIKxpNmqrokVdYt8EeeeOmJ7GWnHXCuSzO8KyR8XY3D9kIZfu3RtYn25Pp40jvqzsqotbwJC+QU6vmQADBPSLIAmXEMRIEOx1Hd7SYax7uc2MZQWq+bHPB9Z4t2kM7bLMyDIGUJiH8ygz18/caCwPeOKL+PPyIgJpRmUfgVD/EiGei4vBH92o9MS64qy5mWRxmxKniocPYpNbomcwNImdRGAEzK1MirvaOPdArraVQ=
before_install:
- gem install travis -v 1.8.8 --no-rdoc --no-ri
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=chapter10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=13.59.162.29
- export PLATFORM_TEST_NAME="chapter10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
