language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - pehulja@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- gem install travis -v 1.8.8 --no-rdoc --no-ri
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=chapter10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=13.59.162.29
- export PLATFORM_TEST_NAME="chapter10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
env:
  global:
  - secure: jeViq48GTpfeHD/piX/FGS1y3X5sUZNhZuxAzSdJz7Y3C2kBUuLjoRoYftNtSDS5mvGljhE6i95WEzqz+aXCaO+imHek7aATcpij3sNNU1wrXmmZXNnQ1RCH1MlBWoFt9L+NCVlTMs/OvO6AG6nfOfBL2ilyTArxv6elV/2yvvL4A4elMVZvShS3UVjbgGZwtyVyq71TL5xCBkmdQPOvZ/hDaIrnfy2U8Z2QAdP1Wun8fO3TbDgXY3MznA53XuOZAIDVy/8OBtoIuSkwI1ZGZX/hsqrX83IRAP3WlUcJc7sK1qWQxPGv+7PTPLDRKMjKTx9Ty47BoKGSUt4rRwzih5EJT8xfVmDslfme5HMHmexAKc5jKaHLlanavzyy0nv94bous/2rGM2w5dqCpOjxrok3hlCUaKEHdXkGcx68DDc1Dn/i4cBl4qmgVxadv/YlZGysnFIFZo1+giu6krPpV0CoM80U8Megw2hJa91hWLieJH6kMN+gQnqtPn7CADGKe8ta+TJ6LYznfIO8sfsrJf1WMHvjMD3rQx7ATjoozkQrT1MMXLGhx6GXSurrmGctV1wqSsmL5xuB3yui+RIUExjhRsqOvvhttje3b7pVwjRMFt/Drb8eV0xsHKp/EgtTHDXZNbrlyIoFtiZX/uz861lhb2AOe6x41Mz/7V4fOvc=
  - secure: Yy+4a5ap+P19LN1t8EoBZ2cARDcHGCd15OLvi6Qg7WdiiR3ybrUM2lN2ym0RIFVJki/QnGilmTYnFWsjSClD5DQK9GC36wfeysltfFuXFLxPH0NZC2PkrdXEtxgw09tNhIfvSFgLdptX8MP8sCtIpj66sIRrndAgcHl+yf1V0CQY3mKby/zCKCqbENB7SGjlFl+R3cjTh8HfLBfy7r1VkIEbpLj1pRHL18JS0qi3yhCpO7su8WkJn+AMcuio3wtOdZFaSMqy8Ce2GK0OL40tQnSZ3u8rNQXNcWGfvsruMFVfIhKstCZEoV5KFKzxLGy9yvYbXYSndwLyMaNgSaog6ipUl6pqAwq8f7JrwprKZJBOljkUmN43kTAiZglDvMVbL4oBkplHnY03KXFfMmbgnyfSC1MQGn61Pik6JDtD3e6AKO1d3eNU0lnmmXRBmbSt39JyNhwN7TLE8Mupp283b9O7J0Aadq0lIGGGX9gcZ+Me1YrCzNJ20vjmnXmf0wijz6CcpcCkbJuoe1D+RAEpMjf4DBNaNPwGW38d7Sm2FFP67NISZgrKx99gxUFVAdfed1ofFXn4QIa7FF67yUQk/ao+PjN6Q9bSYRaT/CFZ59N/c1Z5/Uz3XYfmJFyjasODB5kSSd1GZzFNopZtT5lXs3m+w7cdh0bISauV0REn2xs=
  - secure: gx1F6ukgqLw7KOPZSbMukOyKayc6ZuGTg4kExqHE+2ER8AdbWLG7WmrcbzLAkSv8s48OsvHZb388IlYPc93Bj9gcVSKhj/xUvB5TNY2dURrak2GFD8dUMyiTAQRjrHJgEP5x70TzSi19kZSnsXJdqzz3fYKrc6QfKXCMfxaA74u3YXEuIss5eDcbllH6yAKtJ93dUhsVljCmvNxDz9jOmr1eziuQx6xjgb5XAVQYJ4tmyKrRvhrmitSZ0vId0nNJf7WsUYuwe/sOAhns4TQ7PM3cQZCJ6bkRxkl0ZD61sK3MwxStIXBz4R9SQRcu+Z3niSmqO/K4mkdbBXaR/VifYjcUUgJpfOb52vlqiaTayQRLcO+Xw5fkjigFbfzbVxbKNQX7Axq9i7QYGT+mHCIxODnGo2VfYvBhlV0IT8b4WqvFk2Hci6zy2xuAMAYjQTKI3JoItT/utTLrEzMtrLRNI6jZptwLsBHudcoDra8dUeHbabQsSIskfc+1MbMIt3SU2+CFJCGZ81ynqBo6ys6BBtkU1WEuOw8kU7aZigCph6OevMVjAiNe1h4BqRMx7+A5v+Wuh3vAIVX9h+qJAFmG+Z8L//0CSPpbVlQdeH6jJIlWM862LNoI96xfJg9yTJPcZP96DWiAxb6IrAmZeu3M6H80d5KHPey2RfTOiSQ72/w=
  - secure: K+p4FoYmpwrxrA0ac/2NuSP8eTH5WVp0kaTicUqOx+hLnK/5yYFoFbGQTLvL5MkLWXXCDpuzt83lH52Mfwcmf/Dsecl+h+KJtKuVN/JAbJAor3FhKrmxUsXcsFcmwyK4aQXCz8MAKr9ZKoJLEhexXsyvT510UrELYS3ySaqoFSsUI63nSXucIUZwtQrfxRieFfrNaFg2wOfapYmcvIBRHRJd6AXGf1OAwIEoH38VxNCMo6gL7PDyd5wF37LunnNUiqq6D9f3ug/5nJYZR5lwi0BYLODQ8W1T489WXsi1uJXeucdB8u8NnKwyxoNjIa0f4XPkXiBmCGDCTr3vH6uXOBXwRygg4b1eTywjEvdLa0/QC+5a7rz1/b5C6WynGKI6LaMgARCi3caDeZKTkxfsjfFJpyOba18M2zxR43Tha0uqtZW7/fVlD5PpqdKyqITc+nQRxAUV8sMoInQYYrddj7ir9UURTVQlKKVIjuig3tbuaO4NuMwBdcZmN4rGN7zHOPhfc6RiyYehbC+49HeHow6nbrdTy6Op1nBXe78Iv+/ZSSafwX+sL5ytI7tytO3KTWmicQqWzO6wSGFEtG/Erysnk7POf0mBcaIqF8uHbTX4cwoqRvAE8URdbkf856+TvYAWKWRL+OcU9k9iQNQROD1Kc9EfbGmrsGdmiDEX5f0=
  - secure: kIM8j/UBEz8daAsAHYUrBG9VFx1uZbEvWxyw6orDik0JIZ6rdoNelSnadhUz2IDdx0zdakprI7luzCrs5kyxiVGkQZQsFlDyYaBkW/26jsnOkGyI7ws6zAzqQuI+KAYCm7lN03LrMCyjiv7BFTbT9a3bM7JrJiJ2yFYZtFIbdyGHQmNS7QxS36OrjO9XgVCRcthC4cRMyk7J9XNT45w1NLthxT4ONgjOf5SAFt6PKlWZTNH9viFhebOenZ4b4GsWQqVGzt7abo2GFJATAbZcXzX9VU1NrdClPwrtI/7DHPisbV2+vgSqA/lHWxk/JyNKCdSJZyJdKXyaa/VfpgEqrUt52BfmtwKMzYPzS0QGpfVpLtacKntYDtRKo77zsuO6bD5lfXLQyPYHdt1xO8o4Y0lX9NN3u83bdE4iMQv6Jvxa1smEgI0LmKK8uVfgLTOjoV6XHIxbDmI18UZmI8JyV8o/g8hBHerFiyOdO5uXWkiJwTJDgDfkbdVIWZ4FtfvUlidMmFj9jXqa51EcNeBM2Z+8ZdLweXS7K4Wnz7/BcBMNBwRgqceNMA/VLeaCAozi8L2n/KAitn3/HQWy4C9nLgaYKl2zMWuXO3YqYfRF60Lnv9N6i0QAgyB74BQnqoQiDJivlNn+tcLL07nOtbXr/zrmRHdpNp/ZHTGO6IJYyPw=
