language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - pehulja@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- gem install travis -v 1.8.8 --no-rdoc --no-ri
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=chapter10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=13.59.162.29
- export PLATFORM_TEST_NAME="chapter10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
env:
  global:
  - secure: cr3KcatvE6VdTWrikc2czc7I+Bcdbqd43R1v2+khSnvJo7YPCk51mH9LKltwU1lVkYxc6SBvoGJOJutQvsQ+W+poAP3kuCvV+QxCiEneR6MYM3jHcYwB49111syI/r+n+cecDAXneFIKvCdjQrhW4DI6Q5VFTQDDOly7Ays7flbrrdp8Hz0AHh8dJG8ozKKGX6898m4rGylIOv/E/yKN767O/gNkDjBhpHtOFpr70zFaKot8stnW2fgt+RF0Q5Vx/0HPFcLr/I30Srx/jL7W9Ud6yIcaW3o2SVD9IY1C3TuGYKM8oIvlgq7LSTfqRS7/RGWH4h1tpyG0TF+UoZ6lWleTtyxyuzsce18dX9L108La9YHMD8khYfTTEIJdFbObGmIr7kZEcBTE/4ZIvDw95liy/NcO7ZvJxSTV46Fcwuw+VBDnlIsfmebvjt6VXZ0qFcyJlfEstisBbVjl9JHN17N0D6kvVYcxYQx/8gVDogwJcvw837fZtvEQ5tSDJAdqu4ZCUyl1qd3ZR9nJfTUjEILzBZHMsHCcdduRK9jdTJUgM4C2PGzKJXFsLU65G1/hB2Mt8O/9LX30flF75/kLW3VZd7RS0n9AmWUr+AHjI2PTzHdyK+QwiCJsqE0FCA4UIs98vj0FGFDc/8DnrSuYRUq0PAy3YQrpYFpdOqh66uY=
  - secure: gE2zYM3uF0IWle1paX1/Vso3l9MkBy7UBTkSNXRtHw2LofSR4TDaC4mxBL2YzOmuVJWA7RUSiQ2vnQx4hdE7FXr3FicFu90FQPLybgeH8WXjs8VVO4hM2XTioPuc+lg7WVjUEWZE4HwHufRs3YMkkfZ9NDEu0KJv+c2csrg7E9SbfArYE6Nd7BHqnxD7WXYqlqUZAV8S/pDuMeQfp/TlpEJOswtZ9nZ1RAaEMazV50S/XurhyoWx43CTwjiCiAXeY3ukpStyC68t5l6k4Y0W3e0LL+feQxs8QerO+YaMnWPJumWSVzPm9Yi9e9tU+T6XP2wWRDLzdfpxDczua9w+tHn83TklTAgo3u05ZHsouvr6BHTv/5Q/fCdqpQwX6F/B5VZydbaKfnllgr9sst5kGQO5YT5xxyr0TzxsgAAlXqnu2Vo+hNsBIxzjLeaXbtGL74VlHClAvgdc3LfTiN+BQYkqGBPcGHP5iQEV9U3vhQ0YS93ip+SLpGOfa/2Z5I6Bl/B5o6eEag38quTqoPeBQlVJ2nsj4VZGiGgC7pUw3Lgoq9wRjcwj41IlyoFpeoqJaQf9Uxcr1oVEUsRBpugPjZxZ8ovAYjx/VOfQ3psM1VbrD2YOYKZ6C7UKquPW3lvvGT+6VyIW9OroxMfEIGQt0zlKjAZq8DUSSliZwREZ06E=
  - secure: aTK2R+7/FuG71q/md7rzS/f1VQQNG9jbYfxLGVr03c1LsbvdJw1UVA9cm7mT9cCxfiZF+WmmuuHsH1q5UhNKoijrKHlDE8UMi6tNQgj3ru1j/q6oopks8OMUgueRT51DzeGKFXny998rMcHuBnyUfPAFvGYSu/OoN6ctg0gFtyFEz5U9y0lvSnzSCV2x70aPk+ZGd9WJEEUPwvWGs+WBjPtvbvkeBlLJgkkDq6pfFn7F0rg43n6CPL2d2BVhKjD5utWU/aJMMU+Ws9Q5Rmp3wGqBo8FRVczh3ULcgW26LqYUAxifkWYyM2trqpoXlG/h78aCA1hoBhzY6Z80QlCbSOeo+iKfzuYHTGlLribPkNFMVmFOWhtQAb2WwJMpii7GDlDY5F01UOlmzWuxiiL/Lc8PnnZlMW+BvKKsWkS8XJ8Y5XA/V7MlWkN3X/UQm4fYjBTr9Zd1RWfPt9OGtU1Qh2PF6M1eoEnatgPyZW9JV1LdRbAdFfRj5qmUU7jw+Cb3rmqXNhJZCsANOlbMpNIH5zPEpHUlTFfCP7iLi/DZshNddEbDSlF95RGfYIRKUQkb1yXSFmSA8djq5JZ2Yrj+gYdQsckHMwfdixVY9Y21hhS/C1jQC7rfkrKtar65/jJdR/1L6qdMldR+z2GOmF3DvbLWwRh/iOS4MEItsOKVvAs=
  - secure: V7V8cyinzaB6k2jZ9YLtvmmE2rxx1rdSGtdwj+Geknt8HYl5DbGR8hsYxSb/t3NMZABQmfssVWrHdF3QpmnwHb5gYcek5pS9CjTdj+vqmPtUvlVU8GHgBi3KsoXjU6Hk4KQHIEf0PG42F/EdDudA8RpLbIgRsM9UjU9u7KwdiecMA2C1o+mz08lBhRPbgiGnYEMP2OWE7rrnDlEPQmiA39iqCjLvJEuhSALgSbb9ISsrhdYPmkpXTIQxiFMf+qDMro7UHxWp0OonbvX4AyKh4sXinJMwVEvjs4iAA8NkFt4VASDpdkPzvgQ7y3eeGlUvMH87UTOKu9sAeP+vzxviJHqvMejSQ/cYCLahSZDh04Xudtd1q2q5gfb7AeE1VFUbb/M5q0O0qTh1wuiqAQWvr4DL9cfU/EJrVUrjFPFtHGJ55LvtWm9t4Ct2ePTz7mXKn3v3UQAvwu4Y0lJ3whcHTlyiFj9PhyzaFnDldN0tz271vKry/200c6qt4t+vgkQTVrnC3cZFVs8uTuMQP+KITLZCXa9sR/IadRk4naMVgyFX8ElIskIViBhfeER2/B8nPcy3RFRNEZyNV3KeP4znFh81iUSK6BjYEdPKoTUC69yzqzc/e5UYeqbRR3V10R8l5dymMpXWLR+jOGyzUQWrVNNMe2bKcqnzJxqfdGQefT8=
  - secure: NwCcI87ETLNrj0Es3yyWddob+r77AFBAXvydleeB2pgrIjinDDFpHGCp+zfnxh32axsGFfEfHUZKxPYpQt7DaEyAdAUSAiZ8QBSPUfqI/E/vnUMz98eBIQkE0XYqD4v9oaW9Nn1Y2ZNM5KGdEtHLUStKiqKc0oAlrcEfWcyHf8eWZ27X2uLa2lIjB20nqR1skLk6uTpwvGMROosD2aaztP+UstdD3zOkmTpGIqVN4D7hoV79a3CexHA13cEAASySePC4O73Me5WqVdkB1ExPjqxcxVQgYFy+K+UTzABpuef3l5raOYvfDNS992wKlcod7HxvKBIP2wxNf93SRb8FLXaLZ4VfcbFD0OGdlPOA/lJ3TuxvMnnaBn6mDtlk6KqGdE6NfdsvfQgr+WKjLK82X5/a8Sou+UyRp3Ms7TgxAYI/ZoMMRr2zoD3HPNdqkfmspkojGO7KE3I5HTGj1zdEMXThLNfZz/ujDwujkeUgVupj7DmNT5GbyMmsSPKXtV881w5o3NrHK15RHT9hkhApzyE7D+AQpsDZ91S3c7y7uajUFl/K80TF8XxwiqdfRc2OMiggxV7Rj8h/48V42d35smcvaWntFNXnpGO8wK2+Kkhc27CGNEoeUOUs/eO03HMy0eyDTwoDd4RuGwCfsAA3pIKTInY+o6pYiuFQZmb46io=
